FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

RUN addgroup -S nodeapp && \
    adduser -S nodeapp -G nodeapp && \
    chown -R nodeapp:nodeapp /app

USER nodeapp

EXPOSE 5000

CMD ["node", "index.js"]
